include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    import_of_legacy_library_into_null_safe: false
  exclude:
    - "lib/generated_plugin_registrant.dart"
    - "**.g.dart"
    - "**.freezed.dart"

linter:
  rules:
